name: CustomItems
version: 1.0
main: xyz.kyle.CustomItemsPlugin
api-version: 1.21
commands:
  givecustomitem:
    description: Give a custom item
    usage: / <item_name>
permissions:
  customitems.give:
    description: Allows players to use the givecustomitem command
    default: op